# -*- coding: utf-8 -*-
"""KTPMUD_DV19_1951040086

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11fYI8RxQE3xdDMqSyiy2ijNF9S5cUvh9

Phần 1

Câu 1A. Kiểm tra một mảng cho trước gồm 4 phần tử. Chương trình sẽ tìm tổng số lượng số nguyên tố trong 
mảng đó?
"""

def KT(arr):
    count =0
    for i in arr:
        if(i<2):
            count=count+1
        else:
            for j in range (2,i-1):
                if(i%j==0 and j<i):
                    count= count+1
                    break
    return len(arr)-count
a= [1,5,6,7,11]
print(KT(a))

"""Phần 2

Câu 1
"""

n = float(input("Moi nhap real_number: "))
m = float(input("Moi nhap image_number: "))
class Sothuc :
    def __init__(self,real_number) :
        self.real_number = real_number
    def gttd(self) :
        return (self.real_number *2) * 0.5

class Sophuc(Sothuc) :
    def __init__(self,real_number, image_number) :
        super().__init__(real_number)
        self.image_number = image_number
    def module(self) :
        return (self.image_number**2 + self.real_number**2) ** 0.5

sothuc = Sothuc(n)
print("Tri tuyet doi co gia tri la: ",sothuc.gttd())

sophuc = Sophuc(n,m)
print("module cua so phuc la: ",sophuc.module())